default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blogApp_development
  username: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: blogApp_test
  username: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: blogApp_production
  username: postgres
  host: localhost
  port: 5432
